AppraiseDev/Appraise

EvalView/views.py
Missing changes from #13 updating priming questions for the data tasks to latest version.
=> Update questions in the data assessment tasks

Dashboard/templates/Dashboard/dashboard.html
Fixes #27.
- Add button to copy verification token to clipboard.
=> Added button to copy verification token. This fixes issue #27.

Dashboard/templates/Dashboard/dashboard.html
One team thought this message mean all of their accounts are finished.
=> Reducing the confusion based on WMT

Campaign/management/commands/StartNewCampaign.py
- Unified code block to read a zipped and unzipped json batch file
=> Improve json batch file reading block (StartNewCampaign.py)

Dashboard/models.py
Add Moroccan Arabic (ary) to models.py
=> add Moroccan Arabic

.github/workflows/tests.yml
=> Run GitHub workflow on push to master

EvalView/views.py
- Clarification of annotation guidelines in the data task
=> Updated guidelines in the data task

Dashboard/models.py
Add Lingala and Luganda as new languages
=> add Lingala and Luganda

Dashboard/models.py
=> add Livonian

Dashboard/models.py, EvalView/templates/EvalView/_sqm_instructions.html, EvalView/templates/EvalView/_sqm_slider.html, EvalView/templates/EvalView/direct-assessment-document.html, EvalView/views.py, create_wmt22_signlt_tasks.py
- Changed `deutsch` -> `Deutsch`
- Updated instructions for the text-to-sign direction
- Added a script that generates batches for the SignLT task
=> Updates for WMT22 SignLT

Campaign/models.py, EvalView/templates/EvalView/_sqm_instructions.html, EvalView/templates/EvalView/_sqm_slider.html, EvalView/templates/EvalView/direct-assessment-document.html, EvalView/templates/EvalView/pairwise-assessment-document.html, EvalView/views.py, Examples/Monolingual/README.md, Examples/Monolingual/manifest.json, Examples/MonolingualPairwise/README.md, Examples/MonolingualPairwise/manifest.json, requirements.txt
- Step 2/2 to ensure that we can switch to a single `main` branch soon.
=> Merge `azure-webapp-dev` into `master`

Campaign/models.py, EvalView/templates/EvalView/_sqm_instructions.html, EvalView/templates/EvalView/_sqm_slider.html, EvalView/templates/EvalView/direct-assessment-document.html, EvalView/templates/EvalView/pairwise-assessment-document.html, EvalView/views.py, Examples/Monolingual/README.md, Examples/Monolingual/manifest.json, Examples/MonolingualPairwise/README.md, Examples/MonolingualPairwise/manifest.json, requirements.txt
- Merge `azure-webapp-dev` into `main`
=> Merge `azure-webapp-dev` into `main`

Campaign/admin.py, Campaign/models.py, EvalView/templates/EvalView/_sqm_instructions.html, EvalView/templates/EvalView/_sqm_slider.html, EvalView/templates/EvalView/_video_context.html, EvalView/templates/EvalView/direct-assessment-document.html, EvalView/views.py, create_wmt22_tasks.py
- Add guidelines in German for the task
- Generate and display video context
- Display `Campaign.campaignOptions` in the admin panel
- Remove duplicated code that's likely been created due to automatic merging
=> Updates for WMT22 SignLT task

Dashboard/templates/Dashboard/dashboard.html
=> Update the text on the dashboard to WMT22

Dashboard/models.py, create_wmt22_tasks.py
- Added Yakut language code
- Added an option for generating even number of tasks
- Splitting by tab character explicitly because document IDs may include whitespaces
=> Small updates for WMT22

EvalView/views.py
- Add `ReferenceBased` task option to `Direct` task for setting reference label and language
=> Add task option for reference-based DA tasks

Campaign/management/commands/validatecampaigndata.py, EvalData/models/data_assessment.py, EvalData/models/direct_assessment.py, EvalData/models/direct_assessment_context.py, EvalData/models/direct_assessment_document.py, EvalData/models/multi_modal_assessment.py, EvalData/models/pairwise_assessment.py, EvalData/models/pairwise_assessment_document.py, RegressionTests/run.sh
Follow up to #91 making the changes compatible with Python 3.8.
=> Fix JSON loads for Python <3.9

Dashboard/models.py
Add Maithili and Sanskrit language codes
=> add Maithili and Sanskrit

Campaign/utils.py
=> Clarify error message when init_campaign.py is run for the first time

Dashboard/models.py
=> Add Sepedi (Northern Sotho)

Dashboard/models.py
Add 7 new Indic language codes
=> add new Indic languages

.github/workflows/main.yml, EvalData/management/commands/CreateFakeBadRefs.py, Makefile, requirements-dev.txt, setup.cfg
- Execute all validators directly for full version control
- Add Makefile for easy local execution
- Continue on error (to be changed)
=> Update and make code formatting checks optional

Campaign/management/commands/ComputeWMT23Results.py, EvalData/admin.py, EvalData/models/base_models.py, EvalData/models/pairwise_assessment.py, EvalView/views.py, INSTALL.md, requirements-dev.txt, requirements.txt
- Migration to Django 4.1; latest that supports PostgreSQL 11
=> Migrate to Django 4.1

Campaign/management/commands/ProcessCampaignData.py, EvalData/models/direct_assessment_document.py
@hitokazm, this should fix the creation of document-level campaigns, please merge when you see fit.
=> Fix creating campaigns of Document type due to CommandError: mqm

Dashboard/utils.py
As per email conversation, this fix makes it possible to generate user p-values for ESA by matching on target ID and source text. It copies mechanics of `Campaign/views.py` but only for ESA (not for MQM).
Note that this originally stems from incorrect item ID usage due to my misunderstanding (& lack of documentation) and additional payload in the item type field.
=> hotfix for ESA code generation

EvalView/templates/EvalView/_instructions-esa.html, EvalView/templates/EvalView/_instructions-mqm.html, INSTALL.md
This PR just adds a bit of documentation to `INSTALL.md` about generating the tokens that I didn't know about.
=> Document annotator tokens

EvalView/static/EvalView/js/direct-assessment-document-mqm-esa.js
This PR makes it so that on ESA upload error, the submit button is reenabled afer a while.
=> Catch ESA submission errors

Campaign/views.py
Following the discussion with Tom, this simplifies the upper bound computation.
=> simpler upper bound for annotation time
