Examples/DocLevelDA/README.md, create_wmt19_tasks.py
`create_wmt19_tasks.py` could still generate some BAD items even if `CONTROLS` was set to false from the command line. This PR properly disables quality control if requested.
- Do not generate BAD items if `CONTROLS` is set to false from the command line.
- `CONTROLS` can be disabled via `"0", "false", "off"` too (case insensitive), not only by an empty string `""`.
=> Entirely disable quality control in the task generation script if requested

Campaign/management/commands/ExportSystemScoresToCSV.py, EvalData/models/data_assessment.py, EvalData/models/direct_assessment.py, EvalData/models/direct_assessment_context.py, EvalData/models/direct_assessment_document.py, EvalData/models/pairwise_assessment.py
This PR adds a new option to the export script that, if enabled, adds two new columns into the CSV file with exported scores with batch number and item ID. This will help match exported scores with items from the input JSON batches, especially for pairwise tasks with expanded systems IDs.
Note that item ID is the item ID from the database, not the `_item` field from the batch, because it's not loaded into the database when a campaign is created. But that's sufficient to track back items from the JSON batch.
Related issues: #5 
- Added `--add-batch-info` to `ExportSystemScoresToCSV.py`.
- When enabled, two new columns are added to the exported scores: batch number, and item ID.
- For pairwise tasks, a third column with target ID is added additionally. …
=> Add batch and item IDs into CSV files with exported scores

Campaign/management/commands/ExportSystemScoresToCSV.py
Batches of data assessment tasks contain document URLs that may contain a comma. If so, those rows in the exported CSV file are not properly formatted. This PR fixes that issue by using a CSV writer that quotes fields if necessary, to keep the expected format.
- Generate rows using `csv`, which can automatically quote minimal special characters (https://docs.python.org/3/library/csv.html#csv.QUOTE_MINIMAL)
=> Quote fields with special characters in the CSV export

Campaign/management/commands/init_campaign.py, Campaign/views.py, Dashboard/templates/Dashboard/dashboard.html, Dashboard/utils.py, Dashboard/views.py, EvalData/models/direct_assessment.py, requirements.txt
This pull request adds confirmation tokens that can be used for shallow integration with external crowd-sourcing apps like Toloka. A task confirmation token (UUID4) is displayed on the user's dashboard if the user have completed all assigned tasks. If the user passed the quality control, the valid confirmation token is shown, which is the same as the one exported via `init_campaign.py --task-confirmation-tokens`; otherwise an invalid confirmation token is shown, i.e. it is different than the token generated via `init_campaign.py`.
- Valid or invalid confirmation tokens are generated based on passing or failing the quality control.
- The quality control method is extracted from the campaign status check.
- A confirmation token is shown on the dashboard …
=> Task confirmation tokens for shallow integration with external apps

EvalView/templates/EvalView/pairwise-assessment.html
Fixes #23.
- Adding the 'Match sliders' button.
- Adding tooltips to all buttons mentioning defined access keys.
- Setting focus on the first slider on page load so that it can be changed using left and right arrow keys on keyboard.
- Removing commented out JS code.
=> A button for matching sliders in pairwise tasks

Campaign/management/commands/init_campaign.py
Fixes a bug that made `init_campaign.py` generating identical confirmation tokens for each user.
=> Fix generating confirmation tokens in init_campaign.py

EvalView/templates/EvalView/data-assessment.html
Fixes a bug: some HTML tags included in the source or target texts (e.g. `</form>`) can block the submission button so that it's impossible to finish the task. Thanks for @cfedermann for reporting this issue.
- Replacing `|safe` with `|escape`.
=> Escape source and target texts in data tasks

EvalView/templates/EvalView/data-assessment.html
Instead of `loop.index`. This fixes issue #29.
Fixes #29 .
- Change from `loop.index` to `forloop.counter` which is what Django templates expect.
=> Changed ID generation for radio boxes to using `forloop.counter`

EvalData/management/commands/UpdateEvalDataModels.py, RegressionTests/README.md
Fixes a silly bug which makes `UpdateEvalDataModels` crashing.
- Fixed the function name.
- Fixed a path in `RegressionTests/README.md`
=> Fix incorrect function name in UpdateEvalDataModels

EvalView/templates/EvalView/pairwise-assessment.html
Fixes #42.
- Word differences between two segments are highlighted by default
- Fixed help messages for buttons in the contrastive task view
=> Highlight word differences in pairwise tasks by default

Campaign/management/commands/StartNewCampaign.py
- Allow users to upload batches in a plain and/or zipped json file format. 
=> Add a feature to accept both zipped or non-zipped json batches (StartNewCampaign.py)

Campaign/views.py
Fixes `n/a` p-values on the campaign status page for tasks of type Data. The source of the issue was that the script generating batches for data tasks does not preserve `itemID`s between TGT and BAD counterparts.
- Do not use `itemID` in the key determining pairs of TGT and BAD items if it is a data task result
=> Fix showing p-values on the campaign-status page for data tasks

Campaign/management/commands/init_campaign.py, Campaign/models.py, Campaign/utils.py, Dashboard/utils.py, Dashboard/views.py, EvalData/models/__init__.py
Displays an estimated completion status in percentages for each campaign (i.e. a team) on the team page in the admin panel. It's the `COMPLETION STATUS` column under `admin/Campaign/campaignteam/`
Changes proposed in this pull request:
- Display completion status as the number of completed tasks / required annotations
- Small clean up: moving the global list of task and task type definitions to `EvalData/models`
=> Implement completion status on team pages in the admin panel

requirements.txt
Fixes recent fails in Safety checks, for example: https://github.com/AppraiseDev/Appraise/runs/6725289591?check_suite_focus=true
=> Bump Django to 3.2.13

.gitignore, Dashboard/models.py, EvalView/templates/EvalView/direct-assessment-document.html, EvalView/views.py, Examples/SignLT/README.md, Examples/SignLT/manifest.json
Appraise will host sign language translation evaluation.
- Added language code for DSGS
- Added new keyword to the campaign options: "WMT22SignLT", which triggers interpreting source or target segments as videos
- Added a new example (note that the `batches.json` will be added once we have confirmation that we can use sample videos)
=> Support videos in document-level DA tasks

EvalView/templates/EvalView/_sqm_instructions.html, EvalView/templates/EvalView/_sqm_slider.html, EvalView/templates/EvalView/direct-assessment-document.html, EvalView/templates/EvalView/pairwise-assessment-document.html, EvalView/views.py, Examples/Monolingual/README.md, Examples/Monolingual/manifest.json, Examples/MonolingualPairwise/README.md, Examples/MonolingualPairwise/manifest.json
This PR adds monolingual document-level tasks where the source is not displayed and instructions are different.
- Added `Monolingual` keyword to campaign options in `Document` and `PairwiseDocument` task types
- Updated SQM instructions (will be revised later)
- Added examples for both tasks
=> Monolingual document-level tasks

EvalView/views.py
=> Remove English text from German instructions

requirements.txt
Eliminate psycopg version diff as root cause.
=> Update to latest for psycopg2

Campaign/management/commands/validatecampaigndata.py, EvalData/models/data_assessment.py, EvalData/models/direct_assessment.py, EvalData/models/direct_assessment_context.py, EvalData/models/direct_assessment_document.py, EvalData/models/multi_modal_assessment.py, EvalData/models/pairwise_assessment.py, EvalData/models/pairwise_assessment_document.py
Fixes an exception when running Appraise with Python 3.9.
- `json.loads` does not have `encoding` argument since Python 3.9.
=> Remove encoding='utf-8' from json.loads for Python 3.9

Campaign/views.py
Fixes displaying different numbers of completed annotations on the campaign status pages for document-level tasks. The reason why we have different numbers is that accounts usually have different number of documents. We can simply not count document-level scores to keep the numbers reported consistent across accounts.
- Exclude document-level scores from the total annotations displayed on the campaign status pages
=> Don't count document-level scores in campaign status pages

EvalView/templates/EvalView/direct-assessment-named-entities.html, EvalView/views.py, Examples/DirectNamedEntities/README.md, Examples/DirectNamedEntities/batches.json, Examples/DirectNamedEntities/manifest.json, RegressionTests/tests/examples/example_named_entities.scores.csv.expected, RegressionTests/tests/examples/example_named_entities.users.csv.expected, RegressionTests/tests/examples/test_examples_named_entities.sh
This PR adds a new campaign option to the standard DA task that enables evaluation protocol for named entities. 
- Added `NamedEntitiesEvaluation` campaign option to `Direct` task
- Added an example and regression test
=> Named entities evaluation task

Campaign/management/commands/ComputeWMT21Results.py
Adds 'liv' to `ComputWMT21Results.py`.
=> Add Livonian to the ranking computation script

Campaign/management/commands/init_campaign.py, Campaign/utils.py, EvalView/views.py
Adding "linear" mapping of annotators to tasks for full control of which batches are assigned to whom.
=> Add 'linear' mapping of annotators to tasks

EvalView/views.py
- Do not escape `<br/>` elements if used instead of `<eos>`s
=> Respect <br/>s in pairwise document-level tasks

Dashboard/views.py, EvalView/templates/EvalView/_guidelines_popup.html, EvalView/templates/EvalView/_sqm_instructions.html, EvalView/templates/EvalView/pairwise-assessment.html, EvalView/views.py
- Fix a bug with unbound variables for staff users
- Add paragraph guidelines to segment-level contrastive tasks
=> Add paragraph guidelines to segment-level contrastive tasks

Campaign/tests.py, Campaign/utils.py, Campaign/views.py
This PR should fix issues with too large total annotation times displayed on the campaign status page for PairwiseDocument tasks and potentially also for ESA tasks. In PairwiseDocument tasks, start timestamp is the same for all paragraphs within a document, so a solution was to exclude overlapping portions of paragraph-level annotation times when computing the total.
@hitokazm, please feel free to merge and re-sync the instance.
@zouharvi, FYI. We will be able to confirm if this fix also solves similar issues in ESA campaigns once we pull these changes to the instance and compare campaign status pages in existing campaigns.
=> Fix total annotation time on campaign status page for overlapping timestamps

EvalView/static/EvalView/css/direct-assessment-document-mqm-esa.css, EvalView/templates/EvalView/direct-assessment-document-mqm-esa.html, Examples/DirectMQM/README.md
With minor changes to ESA/MQM view we get multimodal support (resolves #160).
HTML for video (`sourceText`):
```
<video
src="https://samplelib.com/lib/preview/mp4/sample-5s.mp4"
controls
disablepictureinpicture
preload="auto"
controlslist="nodownload"
></video>
```
HTML for audio (`sourceText`):
```
<audio
src='https://samplelib.com/lib/preview/mp3/sample-3s.mp3'
controls controlslist='nodownload'
></audio>
```
[example_small.webm](https://github.com/user-attachments/assets/5df9b2e5-4142-43c5-9c47-7ccd15b02acd)
=> Enable HTML in ESA/MQM sourceText

EvalData/models/direct_assessment_document.py, EvalView/templates/EvalView/direct-assessment-document-mqm-esa.html, EvalView/views.py
- Remove unnecessary data being passed to the ESA template.
- Generating batches with the way they are meant to be generated (#162) breaks the next item loading and displays. This PR fixes that.
@snukky I think we're needlessly losing a lot of compute on this. Do you know how to make JOIN here? The list is exactly 100 items but still would be faster than this lookup that happens on each page load. I tried a few things but I'm quite unfamiliar with Django.
```
all_items = self.items.all()
def get_item_result(id):
return DirectAssessmentDocumentResult.objects.filter(
item__itemID=id,
createdBy=user,
task=self,
).last()
all_items = [(item, get_item_result(item.itemID)) for item in all_items]
```
=> Refactor/Fix ESA template and item loading

Dashboard/templates/Dashboard/base.html, EvalView/static/EvalView/css/direct-assessment-document-mqm-esa.css, EvalView/static/EvalView/js/direct-assessment-document-mqm-esa.js, EvalView/templates/EvalView/direct-assessment-document-mqm-esa.html
This PR makes three changes.
- Adds a new "next document button" state with a tooltip. Thus the button is always visible (#146). The tooltip is unfortunately not visible in the video (Xorg...)
- Fixes a bug where the slider would not be reset.
[Screencast from 2024-07-19 12-39-26.webm](https://github.com/user-attachments/assets/4e74c361-e9cd-42ab-9f4b-beb8b8f5e8b3)
- Adds a slider bubble for more precise scoring. This makes it easier for annotators that e.g. remember that they assigned the score of 70 to a similar error previously.
[Screencast from 2024-07-19 13-01-51.webm](https://github.com/user-attachments/assets/3c12279b-7623-4ffb-b4e9-a91f17e49525)
- A bit unrelated but makes the browser stop requesting a favicon (and hence spamming the console with errors).
=> Annotator Quality of Life

Campaign/views.py, Dashboard/templates/Dashboard/dashboard.html, Dashboard/utils.py, EvalData/models/direct_assessment_document.py, EvalView/static/EvalView/css/direct-assessment-document-mqm-esa.css, EvalView/static/EvalView/js/direct-assessment-document-mqm-esa.js, EvalView/views.py
- This is an attempt at resolving some existing ESA indexing issues discovered during pre-WMT24 testing.
- It also resolves inefficiency in #167.
- Adds warning for low score without errors (Tom's idea).
- Update WMT23 message to WMT24 message in dashboard.
- Slightly change the lisder color so that it's more distinguishable from the white gaps between segments.
- Update/simplify ESA+MQM time computation to new indexing.
=> pre-WMT24 test changes

Dashboard/views.py
During various testing I noticed that when one uses a username that doesn't exist, it crashes Appraise as in the screenshot. This happens because the `authenticate` function assumes that the user will be valid. The reason this is not good is because it tells the user nothing about what the problem is.
This PR is really simple. On incorrect login (username or password), it just redidrects the user to the dashboard which will display empty login.
As a follow-up, a message could be displayed in dashboard that the login failed. It seems that `redirect` can take optional arguments but it's not clear to me how to propagate it to the template so I didn't touch it.
=> Invalid username crashes Appraise

EvalView/views.py
See tracking issue #185. This is not intended as long-term solution. Luckily it seems to affect exactly just one segment.
=> Hotfix escape HTML

.github/workflows/main.yml, EvalData/models/base_models.py, EvalData/models/data_assessment.py, EvalData/models/direct_assessment.py, EvalData/models/direct_assessment_context.py, EvalData/models/direct_assessment_document.py, EvalData/models/multi_modal_assessment.py, EvalData/models/pairwise_assessment.py, EvalData/models/pairwise_assessment_document.py
- Don't encode long lines so that they are legible.
- Drop support for Python <3.9 which is [end-of-life](https://endoflife.date/python). The commit also turned two CRLF files into LF endings.
Before:
After:
=> Misc simplify JSON loading
